language: node_js
node_js:
  - "14"
sudo: required
services:
  - docker
script:
  - docker compose up
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag movie_review_server $DOCKER_USER/movie_review_server:latest
  - docker push $DOCKER_USER/movie_review_server:latest
  - docker tag movie_review_client $DOCKER_USER/movie_review_client:latest
  - docker push $DOCKER_USER/movie_review_client:latest