version: "3.9"

services:

  movie_review_server:
    container_name: movie_review_server
    env_file: .env
    # image: darabosg/movie_review_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - movie_review_app

  movie_review_client:
    container_name: movie_review_client
    env_file: .env
    # image: darabosg/movie_review_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:80
    depends_on:
      - movie_review_server
    networks:
      - movie_review_app

networks:
  movie_review_app: